version: "3.8"

services:
  db:
    image: "postgres:14.0"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: bash scripts/start.sh
    tty: true
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - gems:/gems
    depends_on:
      - db
volumes:
  postgres:
  gems:
