# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

localstack: &localstack
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *localstack
  database: edu_test_development

test:
  <<: *localstack
  database: edu_test_test

production:
  <<: *default
  database: edu_test_production
  username: edu_test
  password: <%= ENV["EDU_TEST_DATABASE_PASSWORD"] %>
